version: "3"
services:
  gas:
    build: .
    volumes:
      - .:/workspace
      - ./.clasprc.json:/root/.clasprc.json
      - /workspace/node_modules
    working_dir: /workspace
    command: tail -f /dev/null