version: "3"
services:
  gas:
    build: .
    volumes:
      - .:/safety_confirmation
      - ./.clasprc.json:/root/.clasprc.json
      - /safety_confirmation/node_modules
    working_dir: /workdir
    command: tail -f /dev/null
